= Versions Node Monitors Plugin

This plugin offers two _node monitors_:

* Remoting Version
* JVM Version

== Remoting Version Node Monitor

NOTE: The link:https://github.com/jenkinsci/remoting/blob/master/README.md[remoting module] handles the network connection between the Jenkins master and agents.

This monitor will disconnect an agent if it is not running the same version of remoting library as the version on the Jenkins master.

== JVM Version Node Monitor

This monitor offers 3 levels of monitoring:

[cols="3", options="header,border"]
|===
| Level
| Description
| Examples

| Default
a| Agent must run a JVM whose **major** version is greater or equal than the one the master is running (strongly recommended minimum).

NOTE: Even without this plugin, it is **critical** to the health of your Jenkins cluster that the agent JVM major version **match** the master JVM major version.
a|
* an agent running Java 7 or less will be disconnected from a Java 8u222 master
* an agent running Java 8u172  will **not** be disconnected from a Java 8u222 master
* an agent running Java 8u222  will **not** be disconnected from a Java 8u172 master
* an agent running Java 8u222  will **not** be disconnected from a Java 8u222 master
* an agent running Java 11.03 will **not** be disconnected from a Java 8u222 master
* an agent running Java 8u222 will be disconnected from a Java 11.03 master
* an agent running Java 11.03 will **not** be disconnected from a Java 11.04 master
* an agent running Java 11.04 will **not** be disconnected from a Java 11.04 master

| Paranoid
| Agent must run a JVM whose **major.minor** version is greater or equal to the master version (avoid issues already seen by users).
a|
* an agent running Java 7 or less will be disconnected from a Java 8u222 master
* an agent running Java 8u172  will be disconnected from a Java 8u222 master
* an agent running Java 8u222  will **not** be disconnected from a Java 8u172 master
* an agent running Java 8u222  will **not** be disconnected from a Java 8u222 master
* an agent running Java 11.03 will be disconnected from a Java 8u222 master
* an agent running Java 8u222 will be disconnected from a Java 11.03 master
* an agent running Java 11.03 will be disconnected from a Java 11.04 master
* an agent running Java 11.04 will **not** be disconnected from a Java 11.04 master

| Paranoid\+\+
| Agent must run a JVM whose version is *exactly* equal to the master version (most paranoid option)
a|
* an agent running Java 7 or less will be disconnected from a Java 8u222 master
* an agent running Java 8u172  will be disconnected from a Java 8u222 master
* an agent running Java 8u222  will be disconnected from a Java 8u172 master
* an agent running Java 8u222  will **not** be disconnected from a Java 8u222 master
* an agent running Java 11.03 will be disconnected from a Java 8u222 master
* an agent running Java 8u222 will be disconnected from a Java 11.03 master
* an agent running Java 11.03 will be disconnected from a Java 11.04 master
* an agent running Java 11.04 will **not** be disconnected from a Java 11.04 master

|===
